export enum EnumAuthError {
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS LOGIN OR PASSWORD IS INCORRECT',
	INVALID_ROLE_CONTEXT = 'INVALID_ROLE_CONTEXT',
	AUTH_SCOPE_NOT_SUPPORTED = 'AUTH_SCOPE_NOT_SUPPORTED',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
	USER_PHONE_ALREADY_EXISTS = 'USER_PHONE_ALREADY_EXISTS',
	INVALID_IDENTIFIER = 'INVALID_IDENTIFIER',
	ROLE_NOT_ALLOWED = 'ROLE_NOT_ALLOWED',
	ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
}
