export enum EnumAuthError {
	INVALID_ROLE_CONTEXT = 'INVALID_ROLE_CONTEXT',
	AUTH_SCOPE_NOT_SUPPORTED = 'AUTH_SCOPE_NOT_SUPPORTED',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	ROLE_NOT_ALLOWED = 'ROLE_NOT_ALLOWED',
}
