FROM node:20-alpine
WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
COPY prisma.config.ts ./

RUN pnpm exec prisma generate

EXPOSE 5555
CMD ["pnpm", "exec", "prisma", "studio", "--port", "5555", "--browser", "none"]
