/* eslint-disable import/no-default-export */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
	schema: 'prisma',
	migrations: {
		path: 'prisma/migrations',
		seed: 'pnpm dlx tsx prisma/seed/seed.ts',
	},
	datasource: {
		url: process.env['DATABASE_URL'],
	},
});
