export const BCRYPT_SALT_ROUNDS = 10;
export const REFRESH_TOKEN_BYTES = 32;

export enum EnumTokenError {
	ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
	ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
	ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
	REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
	REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
	REFRESH_TOKEN_NOT_FOUND = 'REFRESH_TOKEN_NOT_FOUND',
}

export enum EnumTokenConfig {
	JWT_SECRET = 'JWT_SECRET',
	JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
	REFRESH_TOKEN_EXPIRES_IN = 'REFRESH_TOKEN_EXPIRES_IN',
}
